highres:
  model: DANRA
  variables: ['temp', 'prcp']
  full_domain: [589, 789]

lowres:
  model: ERA5
  variables: ['temp', 'prcp', 'cape', 'nwvf', 'ewvf', 'msl', 'z_pl_250', 'z_pl_500', 'z_pl_850', 'z_pl_1000']
  full_domain: [589, 789]

data:
  n_samples: 100
  sample_method: random
  data_path_full:  ${env:DATA_DIR}
  data_path_small: ${env:DATA_DIR_SMALL}
  all_data__dir_name: all # or all_filtered
  all_data__dir_name_small: all # or all_filtered
  split_ratio: [0.7, 0.15, 0.15] # train, valid, test